services:
  - type: web
    name: june-x-session
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node voltah.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
